--
-- PostgreSQL database dump
--

\restrict sVoCc97l6YrJpHKZpfUaeCnJvO6FXZgsPVfBsx1t9LcvAz7CVWcIVObInXMoEnW

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: Genre; Type: TYPE; Schema: public; Owner: radio
--

CREATE TYPE public."Genre" AS ENUM (
    'DEEP_HOUSE',
    'MINIMAL_DEEP_TECH',
    'SOULFUL_HOUSE',
    'DRUM_AND_BASS'
);


ALTER TYPE public."Genre" OWNER TO radio;

--
-- Name: TrackStatus; Type: TYPE; Schema: public; Owner: radio
--

CREATE TYPE public."TrackStatus" AS ENUM (
    'GENERATING',
    'CALIBRATION',
    'BUFFERED',
    'PLAYING',
    'PLAYED',
    'REJECTED',
    'FAILED'
);


ALTER TYPE public."TrackStatus" OWNER TO radio;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Recipe; Type: TABLE; Schema: public; Owner: radio
--

CREATE TABLE public."Recipe" (
    id text NOT NULL,
    genre public."Genre" NOT NULL,
    prompt text NOT NULL,
    approved boolean DEFAULT false NOT NULL,
    "createdAt" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public."Recipe" OWNER TO radio;

--
-- Name: Track; Type: TABLE; Schema: public; Owner: radio
--

CREATE TABLE public."Track" (
    id text NOT NULL,
    title text NOT NULL,
    genre public."Genre" NOT NULL,
    status public."TrackStatus" DEFAULT 'GENERATING'::public."TrackStatus" NOT NULL,
    "audioPath" text,
    "durationSeconds" double precision,
    "minimaxPayload" jsonb NOT NULL,
    "recipeId" text NOT NULL,
    "createdAt" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp(3) without time zone NOT NULL,
    artist text DEFAULT 'Unknown Artist'::text NOT NULL
);


ALTER TABLE public."Track" OWNER TO radio;

--
-- Name: _prisma_migrations; Type: TABLE; Schema: public; Owner: radio
--

CREATE TABLE public._prisma_migrations (
    id character varying(36) NOT NULL,
    checksum character varying(64) NOT NULL,
    finished_at timestamp with time zone,
    migration_name character varying(255) NOT NULL,
    logs text,
    rolled_back_at timestamp with time zone,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    applied_steps_count integer DEFAULT 0 NOT NULL
);


ALTER TABLE public._prisma_migrations OWNER TO radio;

--
-- Data for Name: Recipe; Type: TABLE DATA; Schema: public; Owner: radio
--

COPY public."Recipe" (id, genre, prompt, approved, "createdAt") FROM stdin;
cmtfqfk2y0000ln2i4kd6idwt	DEEP_HOUSE	Fictional artist Night Terrace delivers a soulful Deep House excursion at 126 BPM. Warm Rhodes stabs, muted analog basslines, dubbed-out vocal chops, jazz-funk guitar licks, vinyl crackle textures, classic 909 percussion, swung hi-hats, and progressive filter sweeps. DJ-mixable intro, building groove layers, warm breakdown, deep re-entry, clean outro.	f	2026-08-30 11:34:46.379
cmtfqgff5000fln2ioz69fvq1	DRUM_AND_BASS	Liquid Drum & Bass, 170 BPM, original artist Subphase. Rolling two-step breakbeats, ghost snares, deep reese sub-bass, modular percussion, dub chord stabs. DJ-mixable intro, progressive groove shifts, atmospheric sound design, clean outro.	f	2026-08-30 11:35:26.993
cmtfqfrwb0003ln2ivyk0516w	MINIMAL_DEEP_TECH	120 BPM minimal deep tech microhouse by Lumen Tool. Rolling 909 micro-percussion, dubby warm stabs, deep sub-bass pulses, shifting resonant filters, hypnotic groove loops. DJ-friendly intro, progressive dub builds, no EDM drops, no supersaws. Clean mixable outro.	t	2026-08-30 11:34:56.506
cmtfqfwdk0006ln2ih2ibaml3	DRUM_AND_BASS	Drum & Bass, 173 BPM, Kinetic Vale. Rolling two-step breakbeats, ghost snares, reese sub-bass. DJ-mixable intro, progressive groove changes, deep sound design, clean outro.	t	2026-08-30 11:35:02.312
cmtfqg60d0009ln2ik1zil20z	DEEP_HOUSE	Velvet Current deep house, 120 BPM, 4/4 analog groove. Warm Rhodes chords, dub delays, deep soulful sub bass, filtered disco samples. DJ-mixable intro, progressive percussion layering, analog textures, smooth filter rides, clean outro. No EDM drops, no supersaws.	t	2026-08-30 11:35:14.797
cmtfqgbjm000cln2ikynruxsq	MINIMAL_DEEP_TECH	120 BPM minimal deep tech microhouse by Lumen Tool. Rolling 909 micro-percussion, swung shakers, groovy wooden bongos, dubby chords, analog sub bass, warm stabs. DJ-mixable intro, progressive groove development, stripped breakdown, hypnotic dub textures, sound design, clean outro.	t	2026-08-30 11:35:21.97
cmtfqgyji000iln2i499lx0ay	MINIMAL_DEEP_TECH	Minimal / Deep Tech & Microhouse at 124 BPM by Static Parcel. Rolling microhouse groove, warm dub chords, bouncy sub-bass, shuffled hats, wooden percussion, vinyl texture. DJ-mixable intro, progressive builds, analogue stabs, deep resonant filter sweeps, no supersaws, no EDM drops.	t	2026-08-30 11:35:51.774
cmtfqzxji000xln2ijieq8a5b	DRUM_AND_BASS	Genre: Drum & Bass. 175 BPM. Original fictional artist: Kinetic Vale. Rolling two-step breakbeats, ghost snares, reese sub-bass, dub stabs, modular arps, vinyl crackle, progressive groove builds, sound design FX, DJ-mixable intro, clean outro. No drops, no supersaws.	f	2026-08-30 11:50:36.943
cmtfr0gov0010ln2i0hdcmh07	MINIMAL_DEEP_TECH	Minimal Deep Tech & Microhouse, 120 BPM, original artist Low Orbit. Rolling 4/4 microhouse groove with tight 909 kicks, crisp shuffled hats, dubby chord stabs and warm analog sub bass. DJ-mixable intro, progressive groove development, dub-chamber sound design and clean outro.	f	2026-08-30 11:51:01.759
cmtfqh45c000lln2iiuhtwsqg	DRUM_AND_BASS	Drum & Bass, 171 BPM, Subphase. Rolling two-step breakbeats, ghost snares, deep reese sub-bass, dub chords, crisp 909 kicks, progressive groove evolution, DJ-friendly intro, full breakdown, clean outro. No EDM drops, no supersaws.	t	2026-08-30 11:35:59.04
cmtfql1yo000oln2iw4xzwyq5	MINIMAL_DEEP_TECH	Static Parcel delivers a 123 BPM Minimal / Deep Tech & Microhouse track. Rolling microhouse groove, muted dub chords, 909 micro-shuffles, wooden percussion, tight low-end, analog hiss. DJ-friendly intro, progressive filter movement, no EDM drops, no supersaws. Clean fade outro.	t	2026-08-30 11:39:02.832
cmtfql6ic000rln2ivcydehkb	DRUM_AND_BASS	Liquid Drum & Bass 171 BPM by Vector Rain. Rolling two-step breakbeats, ghost snares, deep reese sub-bass, dub chords. DJ-mixable intro, progressive groove evolution, analogue sound design, clean outro.	t	2026-08-30 11:39:08.724
cmtfqlbcu000uln2i8yo2nm1q	DEEP_HOUSE	Deep House, 120 BPM, original artist Mira Solace. Warm Rhodes chords, deep dub bassline, 4/4 groove with shuffled hats, vinyl texture, progressive filter builds, dub delays, clean DJ-mixable intro and outro. Soulful, hypnotic, late-night basement feel.	t	2026-08-30 11:39:15.006
cmtfrmox80013ln2i659lpukk	DEEP_HOUSE	Deep House 121 BPM, original artist Night Terrace. 4/4 deep house groove, warm Rhodes chords, dusty sampled strings, sub-bass pulses, analogue 909 percussion, soulful vocal chops, deep dub delays, warm filter sweeps, DJ-friendly extended intro, progressive groove layering, smooth clean outro, no EDM drops, no supersaws.	f	2026-08-30 12:08:18.86
cmtfrn2ft0016ln2iajmyggqi	DRUM_AND_BASS	Drum & Bass, 173 BPM, original artist Vector Rain. Rolling two-step breakbeats, ghost snares, deep reese sub-bass, dub chords. DJ-mixable intro, progressive groove changes, deep sound design, clean outro. No EDM drops, no supersaws.	f	2026-08-30 12:08:36.377
cmtfro9bi001cln2iibdet99x	DRUM_AND_BASS	Vector Rain drum & bass 175 BPM. Rolling two-step breakbeats, ghost snares, deep reese sub-bass, dub-stab chords, warm analog pads. DJ-mixable intro with vinyl crackle, progressive groove evolution, modular sound design, clean outro. No EDM drops, no supersaws.	f	2026-08-30 12:09:31.95
cmtfrpet0001iln2i5bwntyfr	DEEP_HOUSE	Deep Soul House at 123 BPM by Mira Solace. 4/4 warm kick, dusty hats, deep sub bass, Rhodes chords, dub delays, vinyl crackle. DJ-mixable intro, progressive groove evolution, smooth harmonic shifts, analog warmth, deep filter movements, clean outro.	f	2026-08-30 12:10:25.716
cmtfrptw8001rln2ic3mqycjp	DRUM_AND_BASS	Drum & Bass, 171 BPM, artist Kinetic Vale. Rolling two-step breakbeats, ghost snares, deep reese sub-bass, dub stabs, modular arpeggios. DJ-mixable intro, progressive groove changes, analog sound design, clean outro. No EDM drops.	f	2026-08-30 12:10:45.272
cmtfrpzff001uln2ivbl0rs06	DEEP_HOUSE	Deep Soul House, 123 BPM, original artist Mira Solace. Warm Rhodes chords, analog 909 groove, dub-saturated bassline, vinyl hiss, and slow filter sweeps. DJ-mixable 16-bar intro, progressive dub-chord stabs, vocal-tinged synth whispers, moody late-night atmosphere, clean filtered outro.	f	2026-08-30 12:10:52.444
cmtfrpoab001oln2ifivz3pec	MINIMAL_DEEP_TECH	124 BPM minimal deep tech and microhouse. Rolling 909 sub-bass, shuffled hats, wooden percussion, dub chords. DJ-friendly intro, progressive build, muted breakdowns, analog synths, clean outro. No EDM drops.	t	2026-08-30 12:10:38.004
cmtfrodto001fln2ihghju6us	MINIMAL_DEEP_TECH	Hypnotic minimal/deep tech house at 125 BPM, 4/4. Rolling dubby sub-bass, crisp 909 clicks, shuffled hats, and atmospheric dub stabs. DJ-mixable intro, progressive layering through the track, textural sound design, deep dub delays, and a clean outro. Original artist Low Orbit.	t	2026-08-30 12:09:37.788
cmtfro5ie0019ln2iyf2giua0	DEEP_HOUSE	Velvet Current deep house, 122 BPM, soulful and hypnotic. 4/4 groove with warm Rhodes chords, muted jazz guitar stabs, dubby analog sub bass and crisp MPC-style percussion. DJ-friendly intro, progressive builds, Detroit-influenced soul samples, filter sweeps, clean outro.	t	2026-08-30 12:09:27.014
cmtfrpjju001lln2ijlt5lub9	DRUM_AND_BASS	Drum & Bass, 170 BPM, fictional artist Vector Rain. Rolling two-step breakbeats, ghost snares, reese sub-bass, crisp 909 kicks, atmospheric pads, dub-influenced delays. DJ-mixable intro, progressive groove evolution, deep sound design, clean outro. No EDM drops, no supersaws.	t	2026-08-30 12:10:31.866
cmtfrqdf30020ln2iuw6gnru6	DRUM_AND_BASS	Atmospheric Drum & Bass at 173 BPM by Subphase. Rolling two-step breaks, ghost snares, deep reese sub-bass. DJ-mixable intro with vinyl texture, progressive groove builds, analog modular sound design, dub-influenced breakdowns, clean outro.	t	2026-08-30 12:11:10.576
cmtfrq7fu001xln2iwh5mn4zo	MINIMAL_DEEP_TECH	Minimal Deep Tech Microhouse, 126 BPM, Low Orbit. Rolling 909 microhouse groove, dubby modular textures, muted chord stabs, shuffled percussion, analog warmth. DJ-mixable intro, progressive groove shifts, stripped sound design, clean outro.	t	2026-08-30 12:11:02.826
cmtg2tn6k0029ln2i7xsrzzrh	DRUM_AND_BASS	Atmospheric Drum & Bass, 170 BPM, Vector Rain. Rolling two-step breakbeats, ghost snares, deep reese sub-bass, metallic percussion, dub delays, crisp 909 kicks. DJ-mixable intro, progressive groove evolution, modular sound design, clean outro. No EDM drops, no supersaws.	f	2026-08-30 17:21:38.972
cmtg2tj4v0026ln2ihpu9absx	DRUM_AND_BASS	Deep atmospheric Drum & Bass 174 BPM by Kinetic Vale. Rolling two-step breakbeats, ghost snares, weighty reese sub-bass, analog modular textures. DJ-friendly intro, progressive groove mutations, deep sound design, no supersaws, no EDM drops, clean mixable outro.	t	2026-08-30 17:21:33.727
cmtg2tf7s0023ln2i3oqdwu31	DRUM_AND_BASS	Subphase delivers a 171 BPM neurofunk Drum & Bass journey. Rolling two-step breakbeats, ghost snares, reese sub-bass, and metallic percussion. DJ-mixable intro, progressive groove changes, modular sound design, and a clean outro. No EDM drops, no supersaws.	t	2026-08-30 17:21:28.648
\.


--
-- Data for Name: Track; Type: TABLE DATA; Schema: public; Owner: radio
--

COPY public."Track" (id, title, genre, status, "audioPath", "durationSeconds", "minimaxPayload", "recipeId", "createdAt", "updatedAt", artist) FROM stdin;
cmtfqg60h000bln2i3jkle26m	Velvet Shift	DEEP_HOUSE	BUFFERED	/data/media/cmtfqg60h000bln2i3jkle26m.mp3	118.909388	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(kick groove)\\n\\n(soft hats)\\n\\n(rhodes chord)\\n\\n(vinyl crackle)\\n\\n[Verse]\\n\\n(warm sub bass)\\n\\n(shaker pulse)\\n\\n(modular stab)\\n\\n(filtered string)\\n\\n[Chorus]\\n\\n(rhodes open)\\n\\n(dub delay)\\n\\n(soulful touch)\\n\\nShift\\n\\nShift\\n\\nShift\\n\\nShift\\n\\n[Verse]\\n\\n(rolling bassline)\\n\\n(woodblock click)\\n\\n(soft pad)\\n\\n(closed hat)\\n\\n[Chorus]\\n\\n(full groove)\\n\\n(resonant filter)\\n\\n(night glow)\\n\\nShift\\n\\nShift\\n\\nShift\\n\\nShift\\n\\n[Hook]\\n\\nShift\\n\\nShift\\n\\n[Bridge]\\n\\n(stripped low-end)\\n\\n(ambient wash)\\n\\n(tape echo)\\n\\n(sparse click)\\n\\n[Verse]\\n\\n(deep pulse)\\n\\n(soul feel)\\n\\n(soft rhythm)\\n\\n(soft groove)\\n\\n[Chorus]\\n\\n(full harmony)\\n\\n(dub return)\\n\\n(filter open)\\n\\nShift\\n\\nShift\\n\\nShift\\n\\nShift\\n\\n[Breakdown]\\n\\n(kick drops)\\n\\n(cavernous echo)\\n\\n(reverb tail)\\n\\n(faded note)\\n\\n[Drop]\\n\\n(sub-bass locks)\\n\\n(crisp kick)\\n\\n(driving hats)\\n\\n(rhodes stab)\\n\\n[Outro]\\n\\n(instruments filter)\\n\\n(isolated kick)\\n\\n(hats fade)\\n\\n(clean tail)", "prompt": "Velvet Current deep house, 120 BPM, 4/4 analog groove. Warm Rhodes chords, dub delays, deep soulful sub bass, filtered disco samples. DJ-mixable intro, progressive percussion layering, analog textures, smooth filter rides, clean outro. No EDM drops, no supersaws.", "bitrate": 256000, "sample_rate": 44100}}	cmtfqg60d0009ln2ik1zil20z	2026-08-30 11:35:14.802	2026-08-30 18:30:18.174	Velvet Current
cmtfqfk350002ln2igj1hzs7v	Velvet Touch	DEEP_HOUSE	REJECTED	/data/media/cmtfqfk350002ln2igj1hzs7v.mp3	151.118367	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(vinyl crackle)\\n\\n(muted kick)\\n\\n(soft Rhodes)\\n\\n(rhythmic pulse)\\n\\n[Verse]\\n\\n(warm bassline)\\n\\n(swung hats)\\n\\n(jazz guitar)\\n\\n(rim clicks)\\n\\n[Chorus]\\n\\n(dub chord stab)\\n\\n(filter open)\\n\\nTouch\\n\\nTouch\\n\\nTouch\\n\\nTouch\\n\\n[Hook]\\n\\nTouch\\n\\nTouch\\n\\n[Bridge]\\n\\n(stripped groove)\\n\\n(ambient pad)\\n\\n(tape hiss)\\n\\n[Drop]\\n\\n(full kick lands)\\n\\n(bassline locks)\\n\\n(percussion ride)\\n\\n[Verse]\\n\\n(sub bass evolves)\\n\\n(closed hats shuffle)\\n\\n(Rhodes chords)\\n\\n(vocal chops)\\n\\n[Chorus]\\n\\n(full harmonic blend)\\n\\n(resonant sweep)\\n\\nTouch\\n\\nTouch\\n\\nTouch\\n\\nTouch\\n\\n[Breakdown]\\n\\n(kick drops out)\\n\\n(cavernous reverb)\\n\\n(echo tails)\\n\\n[Drop]\\n\\n(sub bass returns)\\n\\n(crisp 909 punch)\\n\\n(driving hats)\\n\\n[Outro]\\n\\n(instruments filter down)\\n\\n(isolated kick)\\n\\n(hats fade out)\\n\\n(clean vinyl tail)", "prompt": "Fictional artist Night Terrace delivers a soulful Deep House excursion at 126 BPM. Warm Rhodes stabs, muted analog basslines, dubbed-out vocal chops, jazz-funk guitar licks, vinyl crackle textures, classic 909 percussion, swung hi-hats, and progressive filter sweeps. DJ-mixable intro, building groove layers, warm breakdown, deep re-entry, clean outro.", "bitrate": 256000, "sample_rate": 44100}}	cmtfqfk2y0000ln2i4kd6idwt	2026-08-30 11:34:46.385	2026-08-30 12:09:19.453	Night Terrace
cmtfqfwdp0008ln2irearpe6v	Signal Cascade	DRUM_AND_BASS	BUFFERED	/data/media/cmtfqfwdp0008ln2irearpe6v.mp3	103.88898	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(clean kick)\\n\\n(hats enter)\\n\\n(vinyl crackle)\\n\\n(shaker groove)\\n\\n[Verse]\\n\\n(rolling sub bass)\\n\\n(woodblock clicks)\\n\\n(modular pulse)\\n\\n[Chorus]\\n\\n(dub delay)\\n\\n(filter open)\\n\\nSignal\\n\\nSignal\\n\\nSignal\\n\\nSignal\\n\\n[Hook]\\n\\nSignal\\n\\nSignal\\n\\n[Bridge]\\n\\n(stripped low-end)\\n\\n(ambient wash)\\n\\n(tape delay)\\n\\n[Drop]\\n\\n(heavy sub drops)\\n\\n(kick re-locks)\\n\\n(full percussions)\\n\\n[Verse]\\n\\n(sub bassline evolves)\\n\\n(closed hats shuffle)\\n\\n(dub stabs)\\n\\n[Chorus]\\n\\n(full harmonic groove)\\n\\n(resonant filter)\\n\\nSignal\\n\\nSignal\\n\\nSignal\\n\\nSignal\\n\\n[Breakdown]\\n\\n(kick drops out)\\n\\n(cavernous echo)\\n\\n(reverb tails)\\n\\n[Drop]\\n\\n(sub-bass return)\\n\\n(crisp 909 kick)\\n\\n(driving hats)\\n\\n[Outro]\\n\\n(instruments filter out)\\n\\n(isolated kick)\\n\\n(hats fade)\\n\\n(clean tail)", "prompt": "Drum & Bass, 173 BPM, Kinetic Vale. Rolling two-step breakbeats, ghost snares, reese sub-bass. DJ-mixable intro, progressive groove changes, deep sound design, clean outro.", "bitrate": 256000, "sample_rate": 44100}}	cmtfqfwdk0006ln2ih2ibaml3	2026-08-30 11:35:02.317	2026-08-30 18:34:22.552	Kinetic Vale
cmtfqgff8000hln2i9rz2a3ga	Voltage Pulse	DRUM_AND_BASS	REJECTED	/data/media/cmtfqgff8000hln2i9rz2a3ga.mp3	114.546939	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(vinyl crackle)\\n\\n(soft kick)\\n\\n(ambient pad)\\n\\n(shaker pulse)\\n\\n[Verse]\\n\\n(rolling sub bass)\\n\\n(woodblock clicks)\\n\\n(modular pulse)\\n\\n(ghost snare)\\n\\n[Chorus]\\n\\n(dub delay)\\n\\n(filter open)\\n\\nCurrent\\n\\nCurrent\\n\\nCurrent\\n\\nCurrent\\n\\n[Hook]\\n\\nCurrent\\n\\nCurrent\\n\\n[Bridge]\\n\\n(stripped low-end)\\n\\n(cavernous echo)\\n\\n(tape delay)\\n\\n(soft pluck)\\n\\n[Drop]\\n\\n(heavy sub drops)\\n\\n(kick re-locks)\\n\\n(full percussions)\\n\\n(reese growl)\\n\\n[Verse]\\n\\n(sub bassline evolves)\\n\\n(closed hats shuffle)\\n\\n(dub stabs)\\n\\n(snare roll)\\n\\n[Chorus]\\n\\n(full harmonic groove)\\n\\n(resonant filter)\\n\\nCurrent\\n\\nCurrent\\n\\nCurrent\\n\\nCurrent\\n\\n[Breakdown]\\n\\n(kick drops out)\\n\\n(cavernous echo)\\n\\n(reverb tails)\\n\\n(pad swell)\\n\\n[Drop]\\n\\n(sub-bass return)\\n\\n(crisp 909 kick)\\n\\n(driving hats)\\n\\n(two-step groove)\\n\\n[Outro]\\n\\n(instruments filter out)\\n\\n(isolated kick)\\n\\n(hats fade)\\n\\n(clean tail)", "prompt": "Liquid Drum & Bass, 170 BPM, original artist Subphase. Rolling two-step breakbeats, ghost snares, deep reese sub-bass, modular percussion, dub chord stabs. DJ-mixable intro, progressive groove shifts, atmospheric sound design, clean outro.", "bitrate": 256000, "sample_rate": 44100}}	cmtfqgff5000fln2ioz69fvq1	2026-08-30 11:35:26.996	2026-08-30 11:49:49.488	Subphase
cmtfrq7fy001zln2iejp5wf8b	Orbital Drift	MINIMAL_DEEP_TECH	BUFFERED	/data/media/cmtfrq7fy001zln2iejp5wf8b.mp3	115.382857	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(clean kick)\\n\\n(vinyl crackle)\\n\\n(hats enter)\\n\\n(modular hum)\\n\\n[Verse]\\n\\n(rolling sub)\\n\\n(woodblock pulse)\\n\\n(closed hat groove)\\n\\n(rhodes stab)\\n\\n[Chorus]\\n\\n(filter open)\\n\\n(dub delay)\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\n[Hook]\\n\\nPulse\\n\\nPulse\\n\\n[Bridge]\\n\\n(stripped low-end)\\n\\n(ambient pad)\\n\\n(tape hiss)\\n\\n[Drop]\\n\\n(kick re-locks)\\n\\n(percussion loop)\\n\\n(bass shifts)\\n\\n[Verse]\\n\\n(sub bassline evolves)\\n\\n(rim clicks)\\n\\n(modular pulse)\\n\\n(techno stab)\\n\\n[Chorus]\\n\\n(full groove)\\n\\n(resonant filter)\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\n[Breakdown]\\n\\n(kick drops out)\\n\\n(cavernous echo)\\n\\n(reverb tails)\\n\\n[Drop]\\n\\n(sub-bass return)\\n\\n(crisp 909 kick)\\n\\n(driving hats)\\n\\n[Outro]\\n\\n(instruments filter)\\n\\n(isolated kick)\\n\\n(hats fade)\\n\\n(clean tail)", "prompt": "Minimal Deep Tech Microhouse, 126 BPM, Low Orbit. Rolling 909 microhouse groove, dubby modular textures, muted chord stabs, shuffled percussion, analog warmth. DJ-mixable intro, progressive groove shifts, stripped sound design, clean outro.", "bitrate": 256000, "sample_rate": 44100}}	cmtfrq7fu001xln2iwh5mn4zo	2026-08-30 12:11:02.831	2026-08-30 17:17:37.911	Low Orbit
cmtfr0goy0012ln2ivxozwb1g	Submerged Code	MINIMAL_DEEP_TECH	REJECTED	/data/media/cmtfr0goy0012ln2ivxozwb1g.mp3	170.44898	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(clean kick pulse)\\n\\n(vinyl crackle loop)\\n\\n(soft dub pad)\\n\\n(rim clicks enter)\\n\\n[Verse]\\n\\n(shuffled micro hats)\\n\\n(modular bassline)\\n\\n(woodblock ticks)\\n\\n(chord stab echo)\\n\\n[Chorus]\\n\\n(filter opens wide)\\n\\n(deep tech groove)\\n\\nCode\\n\\nCode\\n\\nCode\\n\\nCode\\n\\n[Hook]\\n\\nCode\\n\\nCode\\n\\n[Bridge]\\n\\n(stripped percussion)\\n\\n(cavernous dub wash)\\n\\n(tape delay hits)\\n\\n(subtle pulse shift)\\n\\n[Drop]\\n\\n(full microhouse kick)\\n\\n(resonant bass lock)\\n\\n(layered dub stabs)\\n\\n(driving shuffled hats)\\n\\n[Verse]\\n\\n(bassline evolves up)\\n\\n(closed hat groove)\\n\\n(soft chord movement)\\n\\n(rim shot accents)\\n\\n[Chorus]\\n\\n(rolling deep tech)\\n\\n(filter sweep rise)\\n\\nCode\\n\\nCode\\n\\nCode\\n\\nCode\\n\\n[Breakdown]\\n\\n(kick drops low)\\n\\n(ambient dub echo)\\n\\n(reverb tails fade)\\n\\n(sparse clicks only)\\n\\n[Drop]\\n\\n(heavy sub return)\\n\\n(crisp 909 punch)\\n\\n(full percussion build)\\n\\n(dub stab groove)\\n\\n[Outro]\\n\\n(instruments filter out)\\n\\n(isolated kick pulse)\\n\\n(hats fade slow)\\n\\n(clean vinyl tail)", "prompt": "Minimal Deep Tech & Microhouse, 120 BPM, original artist Low Orbit. Rolling 4/4 microhouse groove with tight 909 kicks, crisp shuffled hats, dubby chord stabs and warm analog sub bass. DJ-mixable intro, progressive groove development, dub-chamber sound design and clean outro.", "bitrate": 256000, "sample_rate": 44100}}	cmtfr0gov0010ln2i0hdcmh07	2026-08-30 11:51:01.763	2026-08-30 12:09:18.331	Low Orbit
cmtfql1ys000qln2ispr83he6	Echo Code	MINIMAL_DEEP_TECH	BUFFERED	/data/media/cmtfql1ys000qln2ispr83he6.mp3	146.938776	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(vinyl hiss)\\n\\n(kick pulse)\\n\\n(micro hat)\\n\\n(rubber bass)\\n\\n[Verse]\\n\\n(dub chord)\\n\\n(closed hat)\\n\\n(wood block)\\n\\n(modular loop)\\n\\n[Chorus]\\n\\n(filter open)\\n\\n(dub delay)\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\n[Hook]\\n\\nPulse\\n\\nPulse\\n\\n[Bridge]\\n\\n(stripped low-end)\\n\\n(cavernous wash)\\n\\n(tape delay)\\n\\n[Drop]\\n\\n(sub bass moves)\\n\\n(kick re-locks)\\n\\n(shaker groove)\\n\\n[Verse]\\n\\n(sub evolves)\\n\\n(rim shot)\\n\\n(dub stab)\\n\\n(micro shift)\\n\\n[Chorus]\\n\\n(full groove)\\n\\n(resonant filter)\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\n[Breakdown]\\n\\n(kick drops out)\\n\\n(reverb tail)\\n\\n(ambient dub)\\n\\n[Drop]\\n\\n(sub returns)\\n\\n(crisp kick)\\n\\n(driving hat)\\n\\n[Chorus]\\n\\n(full pulse)\\n\\n(deep tech)\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\n[Outro]\\n\\n(filter cutoff)\\n\\n(isolated kick)\\n\\n(hiss fades)\\n\\n(clean tail)", "prompt": "Static Parcel delivers a 123 BPM Minimal / Deep Tech & Microhouse track. Rolling microhouse groove, muted dub chords, 909 micro-shuffles, wooden percussion, tight low-end, analog hiss. DJ-friendly intro, progressive filter movement, no EDM drops, no supersaws. Clean fade outro.", "bitrate": 256000, "sample_rate": 44100}}	cmtfql1yo000oln2iw4xzwyq5	2026-08-30 11:39:02.837	2026-08-30 18:19:34.529	Static Parcel
cmtfqzxjn000zln2iv86227xp	System Pulse	DRUM_AND_BASS	REJECTED	/data/media/cmtfqzxjn000zln2iv86227xp.mp3	171.937959	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(vinyl crackle)\\n\\n(distant kick)\\n\\n(modular pulse)\\n\\n(filtered sub)\\n\\n[Verse]\\n\\n(rolling sub bass)\\n\\n(woodblock clicks)\\n\\n(ghost snares)\\n\\n(tape hiss)\\n\\n[Chorus]\\n\\n(dub delay)\\n\\n(filter open)\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\n[Hook]\\n\\nPulse\\n\\nPulse\\n\\n[Bridge]\\n\\n(stripped low-end)\\n\\n(ambient wash)\\n\\n(dub stabs)\\n\\n(reese swell)\\n\\n[Drop]\\n\\n(heavy sub drops)\\n\\n(kick re-locks)\\n\\n(full percussions)\\n\\n(snare rolls)\\n\\n[Verse]\\n\\n(sub bassline evolves)\\n\\n(closed hats shuffle)\\n\\n(modular arps)\\n\\n(ghost snares)\\n\\n[Chorus]\\n\\n(full harmonic groove)\\n\\n(resonant filter)\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\n[Breakdown]\\n\\n(kick drops out)\\n\\n(cavernous echo)\\n\\n(reverb tails)\\n\\n(ambient pad)\\n\\n[Drop]\\n\\n(sub-bass return)\\n\\n(crisp 909 kick)\\n\\n(driving hats)\\n\\n(rolling breaks)\\n\\n[Outro]\\n\\n(instruments filter out)\\n\\n(isolated kick)\\n\\n(hats fade)\\n\\n(clean tail)", "prompt": "Genre: Drum & Bass. 175 BPM. Original fictional artist: Kinetic Vale. Rolling two-step breakbeats, ghost snares, reese sub-bass, dub stabs, modular arps, vinyl crackle, progressive groove builds, sound design FX, DJ-mixable intro, clean outro. No drops, no supersaws.", "bitrate": 256000, "sample_rate": 44100}}	cmtfqzxji000xln2ijieq8a5b	2026-08-30 11:50:36.948	2026-08-30 12:08:35.612	Kinetic Vale
cmtfql6if000tln2i2ea32qlv	Static Horizon	DRUM_AND_BASS	BUFFERED	/data/media/cmtfql6if000tln2i2ea32qlv.mp3	142.497959	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(vinyl crackle)\\n\\n(filtered wash)\\n\\n(soft pad)\\n\\n(tick rim)\\n\\n[Verse]\\n\\n(rolling sub)\\n\\n(woodblock ticks)\\n\\n(modular pulse)\\n\\n(ghost snare)\\n\\n[Chorus]\\n\\n(dub chords)\\n\\n(resonant filter)\\n\\nShadow\\n\\nShadow\\n\\nShadow\\n\\nShadow\\n\\n[Hook]\\n\\nShadow\\n\\nShadow\\n\\n[Bridge]\\n\\n(stripped low-end)\\n\\n(ambient wash)\\n\\n(tape delay)\\n\\n(pad swells)\\n\\n[Drop]\\n\\n(heavy sub drops)\\n\\n(kick re-locks)\\n\\n(full percussions)\\n\\n(reese growl)\\n\\n[Verse]\\n\\n(sub bassline evolves)\\n\\n(closed hats shuffle)\\n\\n(dub stabs)\\n\\n(snare crack)\\n\\n[Chorus]\\n\\n(full harmonic groove)\\n\\n(resonant filter)\\n\\nShadow\\n\\nShadow\\n\\nShadow\\n\\nShadow\\n\\n[Breakdown]\\n\\n(kick drops out)\\n\\n(cavernous echo)\\n\\n(reverb tails)\\n\\n(soft piano)\\n\\n[Drop]\\n\\n(sub-bass return)\\n\\n(crisp 909 kick)\\n\\n(driving hats)\\n\\n(rolling breaks)\\n\\n[Outro]\\n\\n(instruments filter out)\\n\\n(isolated kick)\\n\\n(hats fade)\\n\\n(clean tail)", "prompt": "Liquid Drum & Bass 171 BPM by Vector Rain. Rolling two-step breakbeats, ghost snares, deep reese sub-bass, dub chords. DJ-mixable intro, progressive groove evolution, analogue sound design, clean outro.", "bitrate": 256000, "sample_rate": 44100}}	cmtfql6ic000rln2ivcydehkb	2026-08-30 11:39:08.727	2026-08-30 18:22:33.678	Vector Rain
cmtfrmoxd0015ln2ioiv5ebau	Velvet Hours	DEEP_HOUSE	REJECTED	/data/media/cmtfrmoxd0015ln2ioiv5ebau.mp3	82.181224	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(soft kick)\\n\\n(rim clicks)\\n\\n(vinyl hiss)\\n\\n(soft pad)\\n\\n[Verse]\\n\\n(deep sub)\\n\\n(rolling hats)\\n\\n(chord stab)\\n\\n(soulful keys)\\n\\n[Chorus]\\n\\n(dub echo)\\n\\n(filter open)\\n\\nSoul\\n\\nSoul\\n\\nSoul\\n\\nSoul\\n\\n[Hook]\\n\\nSoul\\n\\nSoul\\n\\n[Bridge]\\n\\n(stripped low)\\n\\n(ambient glow)\\n\\n(tape delay)\\n\\n[Drop]\\n\\n(heavy sub)\\n\\n(kick locks)\\n\\n(full percussion)\\n\\n[Verse]\\n\\n(sub evolves)\\n\\n(shaker shuffle)\\n\\n(soft stabs)\\n\\n[Chorus]\\n\\n(full harmony)\\n\\n(resonant filter)\\n\\nSoul\\n\\nSoul\\n\\nSoul\\n\\nSoul\\n\\n[Breakdown]\\n\\n(kick drops)\\n\\n(cavernous echo)\\n\\n(reverb tail)\\n\\n[Drop]\\n\\n(sub returns)\\n\\n(crisp 909)\\n\\n(driving hats)\\n\\n[Outro]\\n\\n(filters close)\\n\\n(isolated kick)\\n\\n(hats fade)\\n\\n(clean tail)", "prompt": "Deep House 121 BPM, original artist Night Terrace. 4/4 deep house groove, warm Rhodes chords, dusty sampled strings, sub-bass pulses, analogue 909 percussion, soulful vocal chops, deep dub delays, warm filter sweeps, DJ-friendly extended intro, progressive groove layering, smooth clean outro, no EDM drops, no supersaws.", "bitrate": 256000, "sample_rate": 44100}}	cmtfrmox80013ln2i659lpukk	2026-08-30 12:08:18.865	2026-08-30 12:11:37.559	Night Terrace
cmtfro9bo001eln2iu0eekz8j	Signal Current	DRUM_AND_BASS	REJECTED	/data/media/cmtfro9bo001eln2iu0eekz8j.mp3	91.506939	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(vinyl crackle)\\n\\n(kick drifts)\\n\\n(ambient pad)\\n\\n(sub hum)\\n\\n[Verse]\\n\\n(rolling sub bass)\\n\\n(ghost snare)\\n\\n(modular pulse)\\n\\n(reese drift)\\n\\n[Chorus]\\n\\n(filter open)\\n\\n(dub delay)\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\n[Hook]\\n\\nPulse\\n\\nPulse\\n\\n[Bridge]\\n\\n(stripped low-end)\\n\\n(woodblock clicks)\\n\\n(tape delay)\\n\\n(resonant stab)\\n\\n[Drop]\\n\\n(heavy sub drops)\\n\\n(kick re-locks)\\n\\n(full percussions)\\n\\n(two-step roll)\\n\\n[Verse]\\n\\n(sub bassline evolves)\\n\\n(closed hats shuffle)\\n\\n(dub stabs)\\n\\n(acid line)\\n\\n[Chorus]\\n\\n(full harmonic groove)\\n\\n(resonant filter)\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\n[Breakdown]\\n\\n(kick drops out)\\n\\n(cavernous echo)\\n\\n(reverb tails)\\n\\n(soft pad)\\n\\n[Drop]\\n\\n(sub-bass return)\\n\\n(crisp 909 kick)\\n\\n(driving hats)\\n\\n(reese growls)\\n\\n[Outro]\\n\\n(instruments filter out)\\n\\n(isolated kick)\\n\\n(hats fade)\\n\\n(clean tail)", "prompt": "Vector Rain drum & bass 175 BPM. Rolling two-step breakbeats, ghost snares, deep reese sub-bass, dub-stab chords, warm analog pads. DJ-mixable intro with vinyl crackle, progressive groove evolution, modular sound design, clean outro. No EDM drops, no supersaws.", "bitrate": 256000, "sample_rate": 44100}}	cmtfro9bi001cln2iibdet99x	2026-08-30 12:09:31.956	2026-08-30 17:22:47.292	Vector Rain
cmtfrodtt001hln2i25dhuoor	Orbital Dub	MINIMAL_DEEP_TECH	BUFFERED	/data/media/cmtfrodtt001hln2i25dhuoor.mp3	181.315918	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(clean kick)\\n\\n(vinyl crackle)\\n\\n(soft reverb)\\n\\n(padded tech)\\n\\n[Verse]\\n\\n(rolling sub)\\n\\n(woodblock pulse)\\n\\n(modular loop)\\n\\n(shaker step)\\n\\n[Chorus]\\n\\n(dub delay)\\n\\n(filter open)\\n\\nSpace\\n\\nSpace\\n\\nSpace\\n\\nSpace\\n\\n[Hook]\\n\\nSpace\\n\\nSpace\\n\\n[Bridge]\\n\\n(stripped low-end)\\n\\n(cavernous wash)\\n\\n(tape echo)\\n\\n[Drop]\\n\\n(heavy sub)\\n\\n(kick re-locks)\\n\\n(full perc)\\n\\n[Verse]\\n\\n(sub bassline)\\n\\n(closed hats)\\n\\n(dub stabs)\\n\\n(click groove)\\n\\n[Chorus]\\n\\n(full harmonics)\\n\\n(resonant filter)\\n\\nSpace\\n\\nSpace\\n\\nSpace\\n\\nSpace\\n\\n[Breakdown]\\n\\n(kick drops)\\n\\n(dub chords)\\n\\n(reverb tails)\\n\\n[Drop]\\n\\n(sub return)\\n\\n(crisp nine-oh-nine)\\n\\n(driving hats)\\n\\n[Outro]\\n\\n(instruments filter)\\n\\n(isolated kick)\\n\\n(hats fade)\\n\\n(clean tail)", "prompt": "Hypnotic minimal/deep tech house at 125 BPM, 4/4. Rolling dubby sub-bass, crisp 909 clicks, shuffled hats, and atmospheric dub stabs. DJ-mixable intro, progressive layering through the track, textural sound design, deep dub delays, and a clean outro. Original artist Low Orbit.", "bitrate": 256000, "sample_rate": 44100}}	cmtfrodto001fln2ihghju6us	2026-08-30 12:09:37.793	2026-08-30 17:21:17.484	Low Orbit
cmtfrptwc001tln2ibl17lpx6	Signal Veil	DRUM_AND_BASS	REJECTED	/data/media/cmtfrptwc001tln2ibl17lpx6.mp3	183.954286	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(vinyl crackle)\\n\\n(distant sub)\\n\\n(rim clicks)\\n\\n(cavernous wash)\\n\\n[Verse]\\n\\n(rolling break)\\n\\n(ghost snares)\\n\\n(reese sub)\\n\\n(modular pulse)\\n\\n[Chorus]\\n\\n(dub delay)\\n\\n(filter open)\\n\\nShadow\\n\\nShadow\\n\\nShadow\\n\\nShadow\\n\\n[Hook]\\n\\nShadow\\n\\nShadow\\n\\n[Bridge]\\n\\n(stripped groove)\\n\\n(woodblock ticks)\\n\\n(tape delay)\\n\\n[Drop]\\n\\n(heavy sub)\\n\\n(kick re-locks)\\n\\n(full percussion)\\n\\n[Verse]\\n\\n(sub bassline evolves)\\n\\n(closed hats shuffle)\\n\\n(dub stabs)\\n\\n[Chorus]\\n\\n(full harmonic groove)\\n\\n(resonant filter)\\n\\nShadow\\n\\nShadow\\n\\nShadow\\n\\nShadow\\n\\n[Breakdown]\\n\\n(kick drops out)\\n\\n(cavernous echo)\\n\\n(reverb tails)\\n\\n[Drop]\\n\\n(sub bass return)\\n\\n(crisp 909 kick)\\n\\n(driving hats)\\n\\n[Outro]\\n\\n(instruments filter)\\n\\n(isolated kick)\\n\\n(hats fade)\\n\\n(clean tail)", "prompt": "Drum & Bass, 171 BPM, artist Kinetic Vale. Rolling two-step breakbeats, ghost snares, deep reese sub-bass, dub stabs, modular arpeggios. DJ-mixable intro, progressive groove changes, analog sound design, clean outro. No EDM drops.", "bitrate": 256000, "sample_rate": 44100}}	cmtfrptw8001rln2ic3mqycjp	2026-08-30 12:10:45.277	2026-08-30 17:18:23.088	Kinetic Vale
cmtfrpoag001qln2il1ni1vof	Silent Orbit	MINIMAL_DEEP_TECH	BUFFERED	/data/media/cmtfrpoag001qln2il1ni1vof.mp3	90.932245	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(clean kick)\\n\\n(hats enter)\\n\\n(vinyl crackle)\\n\\n(shaker groove)\\n\\n[Verse]\\n\\n(rolling sub bass)\\n\\n(woodblock clicks)\\n\\n(modular pulse)\\n\\n[Chorus]\\n\\n(dub delay)\\n\\n(filter open)\\n\\nSpace\\n\\nSpace\\n\\nSpace\\n\\nSpace\\n\\n[Hook]\\n\\nSpace\\n\\nSpace\\n\\n[Bridge]\\n\\n(stripped low-end)\\n\\n(ambient wash)\\n\\n(tape delay)\\n\\n[Drop]\\n\\n(heavy sub drops)\\n\\n(kick re-locks)\\n\\n(full percussions)\\n\\n[Verse]\\n\\n(sub bassline evolves)\\n\\n(closed hats shuffle)\\n\\n(dub stabs)\\n\\n[Chorus]\\n\\n(full harmonic groove)\\n\\n(resonant filter)\\n\\nSpace\\n\\nSpace\\n\\nSpace\\n\\nSpace\\n\\n[Breakdown]\\n\\n(kick drops out)\\n\\n(cavernous echo)\\n\\n(reverb tails)\\n\\n[Drop]\\n\\n(sub-bass return)\\n\\n(crisp 909 kick)\\n\\n(driving hats)\\n\\n[Outro]\\n\\n(instruments filter out)\\n\\n(isolated kick)\\n\\n(hats fade)\\n\\n(clean tail)", "prompt": "124 BPM minimal deep tech and microhouse. Rolling 909 sub-bass, shuffled hats, wooden percussion, dub chords. DJ-friendly intro, progressive build, muted breakdowns, analog synths, clean outro. No EDM drops.", "bitrate": 256000, "sample_rate": 44100}}	cmtfrpoab001oln2ifivz3pec	2026-08-30 12:10:38.008	2026-08-30 17:19:04.679	Low Orbit
cmtfrpjjw001nln2ijq3i0kri	Cipher Pulse	DRUM_AND_BASS	BUFFERED	/data/media/cmtfrpjjw001nln2ijq3i0kri.mp3	135.131429	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(vinyl hiss)\\n\\n(distant sirens)\\n\\n(soft pads)\\n\\n(sub hum)\\n\\n[Verse]\\n\\n(reese bass)\\n\\n(rolling breaks)\\n\\n(ghost snares)\\n\\n(closed hats)\\n\\n[Chorus]\\n\\n(filter open)\\n\\n(pad swell)\\n\\nShadow\\n\\nShadow\\n\\nShadow\\n\\nShadow\\n\\n[Hook]\\n\\nShadow\\n\\nShadow\\n\\n[Bridge]\\n\\n(stripped back)\\n\\n(ambient texture)\\n\\n(tape delay)\\n\\n[Drop]\\n\\n(heavy sub)\\n\\n(kick locks)\\n\\n(full breaks)\\n\\n[Verse]\\n\\n(bass evolves)\\n\\n(rim shots)\\n\\n(modular stabs)\\n\\n[Chorus]\\n\\n(full groove)\\n\\n(resonant filter)\\n\\nShadow\\n\\nShadow\\n\\nShadow\\n\\nShadow\\n\\n[Breakdown]\\n\\n(kick drops)\\n\\n(cavernous reverb)\\n\\n(echo tails)\\n\\n[Drop]\\n\\n(sub returns)\\n\\n(crisp kick)\\n\\n(driving hats)\\n\\n[Outro]\\n\\n(filters close)\\n\\n(isolated kick)\\n\\n(hats fade)\\n\\n(clean tail)", "prompt": "Drum & Bass, 170 BPM, fictional artist Vector Rain. Rolling two-step breakbeats, ghost snares, reese sub-bass, crisp 909 kicks, atmospheric pads, dub-influenced delays. DJ-mixable intro, progressive groove evolution, deep sound design, clean outro. No EDM drops, no supersaws.", "bitrate": 256000, "sample_rate": 44100}}	cmtfrpjju001lln2ijlt5lub9	2026-08-30 12:10:31.869	2026-08-30 17:22:37.737	Vector Rain
cmtfrn2fw0018ln2iv8dslyhq	Signal Current	DRUM_AND_BASS	REJECTED	/data/media/cmtfrn2fw0018ln2iv8dslyhq.mp3	122.148571	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(vinyl crackle)\\n\\n(soft pad)\\n\\n(distant sub)\\n\\n(rim clicks)\\n\\n[Verse]\\n\\n(rolling sub bass)\\n\\n(ghost snares)\\n\\n(reese movement)\\n\\n(modular pulse)\\n\\n[Chorus]\\n\\n(filter opens)\\n\\n(dub chords)\\n\\nRush\\n\\nRush\\n\\nRush\\n\\nRush\\n\\n[Hook]\\n\\nRush\\n\\nRush\\n\\n[Bridge]\\n\\n(stripped low-end)\\n\\n(ambient wash)\\n\\n(tape delay)\\n\\n(bass shift)\\n\\n[Drop]\\n\\n(heavy sub drops)\\n\\n(kick re-locks)\\n\\n(full percussions)\\n\\n(break changes)\\n\\n[Verse]\\n\\n(sub bassline evolves)\\n\\n(closed hats shuffle)\\n\\n(dub stabs)\\n\\n(pad swells)\\n\\n[Chorus]\\n\\n(full harmonic groove)\\n\\n(resonant filter)\\n\\nRush\\n\\nRush\\n\\nRush\\n\\nRush\\n\\n[Breakdown]\\n\\n(kick drops out)\\n\\n(cavernous echo)\\n\\n(reverb tails)\\n\\n(pitch rise)\\n\\n[Drop]\\n\\n(sub-bass return)\\n\\n(crisp 909 kick)\\n\\n(driving hats)\\n\\n(reese rebuilds)\\n\\n[Chorus]\\n\\n(dense layered groove)\\n\\n(heavy pulse)\\n\\nRush\\n\\nRush\\n\\nRush\\n\\nRush\\n\\n[Outro]\\n\\n(instruments filter out)\\n\\n(isolated kick)\\n\\n(hats fade)\\n\\n(clean tail)", "prompt": "Drum & Bass, 173 BPM, original artist Vector Rain. Rolling two-step breakbeats, ghost snares, deep reese sub-bass, dub chords. DJ-mixable intro, progressive groove changes, deep sound design, clean outro. No EDM drops, no supersaws.", "bitrate": 256000, "sample_rate": 44100}}	cmtfrn2ft0016ln2iajmyggqi	2026-08-30 12:08:36.38	2026-08-30 12:12:15.293	Vector Rain
cmtfrpzfk001wln2i9tbq08us	Midnight Glow	DEEP_HOUSE	REJECTED	/data/media/cmtfrpzfk001wln2i9tbq08us.mp3	182.151837	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(soft Rhodes)\\n\\n(909 kick)\\n\\n(vinyl hiss)\\n\\n(muted shaker)\\n\\n[Verse]\\n\\n(deep sub)\\n\\n(soulful hats)\\n\\n(woodblock pulse)\\n\\n(modular chord)\\n\\n[Chorus]\\n\\n(full Rhodes)\\n\\n(filter open)\\n\\nShift\\n\\nShift\\n\\nShift\\n\\nShift\\n\\n[Hook]\\n\\nShift\\n\\nShift\\n\\n[Bridge]\\n\\n(stripped groove)\\n\\n(ambient pad)\\n\\n(tape delay)\\n\\n(dub chord)\\n\\n[Verse]\\n\\n(walking bass)\\n\\n(closed hats)\\n\\n(soft vocal)\\n\\n(rim clicks)\\n\\n[Chorus]\\n\\n(harmonic lift)\\n\\n(resonant filter)\\n\\nShift\\n\\nShift\\n\\nShift\\n\\nShift\\n\\n[Breakdown]\\n\\n(kick drops)\\n\\n(cavernous echo)\\n\\n(reverb wash)\\n\\n(rhodes tail)\\n\\n[Drop]\\n\\n(909 return)\\n\\n(deep sub)\\n\\n(shaker groove)\\n\\n(vocal chant)\\n\\n[Chorus]\\n\\n(full harmony)\\n\\n(filter sweep)\\n\\nShift\\n\\nShift\\n\\nShift\\n\\nShift\\n\\n[Bridge]\\n\\n(low-end pulse)\\n\\n(dub stabs)\\n\\n(ambient texture)\\n\\n(soft claps)\\n\\n[Verse]\\n\\n(bassline evolves)\\n\\n(muted percussion)\\n\\n(modular pulse)\\n\\n(rhodes chords)\\n\\n[Chorus]\\n\\n(soulful peak)\\n\\n(filter open)\\n\\nShift\\n\\nShift\\n\\nShift\\n\\nShift\\n\\n[Breakdown]\\n\\n(kick leaves)\\n\\n(pad swells)\\n\\n(echo tails)\\n\\n(vinyl crackle)\\n\\n[Outro]\\n\\n(filter closing)\\n\\n(isolated kick)\\n\\n(hats fade)\\n\\n(clean tail)", "prompt": "Deep Soul House, 123 BPM, original artist Mira Solace. Warm Rhodes chords, analog 909 groove, dub-saturated bassline, vinyl hiss, and slow filter sweeps. DJ-mixable 16-bar intro, progressive dub-chord stabs, vocal-tinged synth whispers, moody late-night atmosphere, clean filtered outro.", "bitrate": 256000, "sample_rate": 44100}}	cmtfrpzff001uln2ivbl0rs06	2026-08-30 12:10:52.448	2026-08-30 17:17:53.324	Mira Solace
cmtfro5ii001bln2ia3bansve	Velvet Night Shift	DEEP_HOUSE	BUFFERED	/data/media/cmtfro5ii001bln2ia3bansve.mp3	102.635102	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(soft Rhodes)\\n\\n(vinyl noise)\\n\\n(rim click)\\n\\n(kick pulse)\\n\\n[Verse]\\n\\n(jazzy guitar)\\n\\n(deep sub)\\n\\n(soft shaker)\\n\\n(clap ghost)\\n\\n[Chorus]\\n\\n(filter open)\\n\\n(chord stab)\\n\\nGlow\\n\\nGlow\\n\\nGlow\\n\\nGlow\\n\\n[Verse]\\n\\n(soulful pad)\\n\\n(rolling bass)\\n\\n(snap groove)\\n\\n(hi-pass sweep)\\n\\n[Chorus]\\n\\n(full harmonic)\\n\\n(resonant open)\\n\\nGlow\\n\\nGlow\\n\\nGlow\\n\\nGlow\\n\\n[Bridge]\\n\\n(stripped low-end)\\n\\n(ambient wash)\\n\\n(tape delay)\\n\\n(rhodes echo)\\n\\n[Drop]\\n\\n(heavy sub)\\n\\n(kick locks)\\n\\n(ride enter)\\n\\n(full groove)\\n\\n[Verse]\\n\\n(bassline evolves)\\n\\n(closed hats)\\n\\n(dub chord)\\n\\n(percussion layer)\\n\\n[Chorus]\\n\\n(full deep feel)\\n\\n(filter sweep)\\n\\nGlow\\n\\nGlow\\n\\nGlow\\n\\nGlow\\n\\n[Breakdown]\\n\\n(kick drops)\\n\\n(cavernous echo)\\n\\n(reverb tail)\\n\\n(pad sustain)\\n\\n[Drop]\\n\\n(sub return)\\n\\n(crisp kick)\\n\\n(driving hats)\\n\\n(chord rebuild)\\n\\n[Outro]\\n\\n(instruments filter)\\n\\n(isolated kick)\\n\\n(hats fade)\\n\\n(clean tail)", "prompt": "Velvet Current deep house, 122 BPM, soulful and hypnotic. 4/4 groove with warm Rhodes chords, muted jazz guitar stabs, dubby analog sub bass and crisp MPC-style percussion. DJ-friendly intro, progressive builds, Detroit-influenced soul samples, filter sweeps, clean outro.", "bitrate": 256000, "sample_rate": 44100}}	cmtfro5ie0019ln2iyf2giua0	2026-08-30 12:09:27.018	2026-08-30 17:22:18.428	Velvet Current
cmtg2tn6p002bln2ib60ij9gx	Ghost Frequency	DRUM_AND_BASS	REJECTED	/data/media/cmtg2tn6p002bln2ib60ij9gx.mp3	163.813878	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(clean vinyl crackle)\\n\\n(distant rain texture)\\n\\n(soft hats)\\n\\n(sub bass hum)\\n\\n[Verse]\\n\\n(rolling breakbeat)\\n\\n(ghost snare hits)\\n\\n(modular pulse)\\n\\n(reese sub)\\n\\n[Chorus]\\n\\n(dub stab echoes)\\n\\n(filter sweep open)\\n\\nSignal\\n\\nSignal\\n\\nSignal\\n\\nSignal\\n\\n[Hook]\\n\\nSignal\\n\\nSignal\\n\\n[Bridge]\\n\\n(stripped percussion)\\n\\n(cavernous reverb)\\n\\n(tape delay pulse)\\n\\n(ambient pads)\\n\\n[Drop]\\n\\n(heavy sub drops)\\n\\n(kick re-locks)\\n\\n(full percussion)\\n\\n(metallic shakers)\\n\\n[Verse]\\n\\n(sub bassline evolves)\\n\\n(closed hats shuffle)\\n\\n(woodblock clicks)\\n\\n(resonant stab)\\n\\n[Chorus]\\n\\n(full harmonic groove)\\n\\n(sweep filter open)\\n\\nSignal\\n\\nSignal\\n\\nSignal\\n\\nSignal\\n\\n[Breakdown]\\n\\n(kick drops out)\\n\\n(cavernous echo)\\n\\n(reverb tails)\\n\\n(distant hats)\\n\\n[Drop]\\n\\n(sub-bass return)\\n\\n(crisp 909 kick)\\n\\n(driving hats)\\n\\n(two-step groove)\\n\\n[Chorus]\\n\\n(full harmonic drive)\\n\\n(filter sweep rise)\\n\\nSignal\\n\\nSignal\\n\\nSignal\\n\\nSignal\\n\\n[Bridge]\\n\\n(stripped low-end)\\n\\n(ambient wash)\\n\\n(modular bleeps)\\n\\n(tape delay loop)\\n\\n[Outro]\\n\\n(instruments filter out)\\n\\n(isolated kick)\\n\\n(hats fade)\\n\\n(clean vinyl tail)", "prompt": "Atmospheric Drum & Bass, 170 BPM, Vector Rain. Rolling two-step breakbeats, ghost snares, deep reese sub-bass, metallic percussion, dub delays, crisp 909 kicks. DJ-mixable intro, progressive groove evolution, modular sound design, clean outro. No EDM drops, no supersaws.", "bitrate": 256000, "sample_rate": 44100}}	cmtg2tn6k0029ln2i7xsrzzrh	2026-08-30 17:21:38.977	2026-08-30 17:32:00.1	Vector Rain
cmtfrqdf90022ln2ilrdwz6q1	Voltage Pulse	DRUM_AND_BASS	BUFFERED	/data/media/cmtfrqdf90022ln2ilrdwz6q1.mp3	183.510204	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(vinyl crackle)\\n\\n(distant hats)\\n\\n(ambient pad)\\n\\n(sub hum)\\n\\n[Verse]\\n\\n(rolling breaks)\\n\\n(reese sub)\\n\\n(ghost snares)\\n\\n(modular pulse)\\n\\n[Chorus]\\n\\n(full groove)\\n\\n(filter sweep)\\n\\n(Pulse Pulse)\\n\\n(Pulse Pulse)\\n\\n(Pulse Pulse)\\n\\n(Pulse Pulse)\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\n[Hook]\\n\\n(sub weight)\\n\\n(rising tension)\\n\\nPulse\\n\\nPulse\\n\\n[Bridge]\\n\\n(stripped back)\\n\\n(tape echo)\\n\\n(soft pad)\\n\\n(woodblock ticks)\\n\\n[Drop]\\n\\n(heavy reese)\\n\\n(kick locks)\\n\\n(rolling hats)\\n\\n(bass evolves)\\n\\n[Verse]\\n\\n(sub bassline)\\n\\n(closed hats)\\n\\n(dub stabs)\\n\\n(ghost snare)\\n\\n[Chorus]\\n\\n(full harmonic)\\n\\n(resonant filter)\\n\\n(Pulse Pulse)\\n\\n(Pulse Pulse)\\n\\n(Pulse Pulse)\\n\\n(Pulse Pulse)\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\n[Breakdown]\\n\\n(kick drops)\\n\\n(cavernous echo)\\n\\n(reverb tails)\\n\\n(ambient drift)\\n\\n[Drop]\\n\\n(sub returns)\\n\\n(crisp break)\\n\\n(driving hats)\\n\\n(full weight)\\n\\n[Chorus]\\n\\n(full harmonic)\\n\\n(resonant filter)\\n\\n(Pulse Pulse)\\n\\n(Pulse Pulse)\\n\\n(Pulse Pulse)\\n\\n(Pulse Pulse)\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\n[Breakdown]\\n\\n(kick drops)\\n\\n(cavernous echo)\\n\\n(reverb tails)\\n\\n(ambient drift)\\n\\n[Chorus]\\n\\n(full harmonic)\\n\\n(resonant filter)\\n\\n(Pulse Pulse)\\n\\n(Pulse Pulse)\\n\\n(Pulse Pulse)\\n\\n(Pulse Pulse)\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\n[Outro]\\n\\n(instruments fade)\\n\\n(isolated kick)\\n\\n(hats dissolve)\\n\\n(clean tail)", "prompt": "Atmospheric Drum & Bass at 173 BPM by Subphase. Rolling two-step breaks, ghost snares, deep reese sub-bass. DJ-mixable intro with vinyl texture, progressive groove builds, analog modular sound design, dub-influenced breakdowns, clean outro.", "bitrate": 256000, "sample_rate": 44100}}	cmtfrqdf30020ln2iuw6gnru6	2026-08-30 12:11:10.581	2026-08-30 17:16:42.638	Subphase
cmtg2tj4y0028ln2ib47wzaa6	Static Charge	DRUM_AND_BASS	BUFFERED	/data/media/cmtg2tj4y0028ln2ib47wzaa6.mp3	121.547755	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(vinyl crackle)\\n\\n(faint hum)\\n\\n(distant kick)\\n\\n(rolling hats)\\n\\n[Verse]\\n\\n(reese sub)\\n\\n(ghost snares)\\n\\n(modular pulse)\\n\\n(dub echo)\\n\\n[Chorus]\\n\\n(filter sweep)\\n\\n(rolling break)\\n\\nCharge\\n\\nCharge\\n\\nCharge\\n\\nCharge\\n\\n[Hook]\\n\\nCharge\\n\\nCharge\\n\\n[Bridge]\\n\\n(stripped bass)\\n\\n(ambient pad)\\n\\n(tape hiss)\\n\\n(sub rumble)\\n\\n[Drop]\\n\\n(heavy sub)\\n\\n(kick locks)\\n\\n(full breaks)\\n\\n(percussion shifts)\\n\\n[Verse]\\n\\n(bassline mutates)\\n\\n(shuffled hats)\\n\\n(woodblock clicks)\\n\\n(dub stabs)\\n\\n[Chorus]\\n\\n(full harmonic groove)\\n\\n(resonant filter)\\n\\nCharge\\n\\nCharge\\n\\nCharge\\n\\nCharge\\n\\n[Breakdown]\\n\\n(kick drops)\\n\\n(cavernous reverb)\\n\\n(echo tails)\\n\\n(silence looms)\\n\\n[Drop]\\n\\n(sub returns)\\n\\n(crisp 909 kick)\\n\\n(driving hats)\\n\\n(rolling breaks)\\n\\n[Outro]\\n\\n(filters close)\\n\\n(isolated kick)\\n\\n(hats fade)\\n\\n(clean tail)", "prompt": "Deep atmospheric Drum & Bass 174 BPM by Kinetic Vale. Rolling two-step breakbeats, ghost snares, weighty reese sub-bass, analog modular textures. DJ-friendly intro, progressive groove mutations, deep sound design, no supersaws, no EDM drops, clean mixable outro.", "bitrate": 256000, "sample_rate": 44100}}	cmtg2tj4v0026ln2ihpu9absx	2026-08-30 17:21:33.73	2026-08-30 17:31:02.612	Kinetic Vale
cmtfrpet3001kln2ikb0z6aw6	Velvet Glow	DEEP_HOUSE	REJECTED	/data/media/cmtfrpet3001kln2ikb0z6aw6.mp3	175.673469	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(soft kick pulse)\\n\\n(vinyl crackle texture)\\n\\n(distant Rhodes chord)\\n\\n(rim shot groove)\\n\\n[Verse]\\n\\n(rolling sub bass)\\n\\n(closed hats shuffle)\\n\\n(modular pulse rhythm)\\n\\n(Pre-Chorus)\\n\\n(filter slowly opens)\\n\\n(dub delay echoes)\\n\\n(tape hiss warmth)\\n\\n[Chorus]\\n\\n(full harmonic groove)\\n\\n(resonant filter sweep)\\n\\nGlow\\n\\nGlow\\n\\nGlow\\n\\nGlow\\n\\n[Hook]\\n\\nGlow\\n\\nGlow\\n\\n[Verse]\\n\\n(sub bassline evolves)\\n\\n(woodblock clicks)\\n\\n(padded synth chord)\\n\\n(soft shaker groove)\\n\\n(Pre-Chorus)\\n\\n(chord stabs echo)\\n\\n(filter rises up)\\n\\n(ambient pad wash)\\n\\n[Chorus]\\n\\n(full deep rhythm)\\n\\n(dub delay tail)\\n\\nGlow\\n\\nGlow\\n\\nGlow\\n\\nGlow\\n\\n[Bridge]\\n\\n(stripped low-end)\\n\\n(ambient reverb)\\n\\n(soft Rhodes keys)\\n\\n(gentle kick pulse)\\n\\n[Breakdown]\\n\\n(kick drops out)\\n\\n(cavernous echo)\\n\\n(reverb tails fade)\\n\\n(pad sustains)\\n\\n[Chorus]\\n\\n(full harmonic groove)\\n\\n(resonant filter sweep)\\n\\nGlow\\n\\nGlow\\n\\nGlow\\n\\nGlow\\n\\n[Drop]\\n\\n(heavy sub drops)\\n\\n(kick re-locks)\\n\\n(full percussions)\\n\\n(open hats swing)\\n\\n[Verse]\\n\\n(deep bass returns)\\n\\n(soft chord stab)\\n\\n(filter movement)\\n\\n(dub echo pulse)\\n\\n[Chorus]\\n\\n(full harmonic groove)\\n\\n(resonant filter sweep)\\n\\nGlow\\n\\nGlow\\n\\nGlow\\n\\nGlow\\n\\n[Outro]\\n\\n(instruments filter out)\\n\\n(isolated kick)\\n\\n(hats fade slowly)\\n\\n(clean tail)\\n\\n(vinyl crackle ends)", "prompt": "Deep Soul House at 123 BPM by Mira Solace. 4/4 warm kick, dusty hats, deep sub bass, Rhodes chords, dub delays, vinyl crackle. DJ-mixable intro, progressive groove evolution, smooth harmonic shifts, analog warmth, deep filter movements, clean outro.", "bitrate": 256000, "sample_rate": 44100}}	cmtfrpet0001iln2i5bwntyfr	2026-08-30 12:10:25.72	2026-08-30 17:22:42.844	Mira Solace
cmtg2tf7y0025ln2irs13p8le	Voltage Pulse	DRUM_AND_BASS	BUFFERED	/data/media/cmtg2tf7y0025ln2irs13p8le.mp3	194.533878	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(clean kick pulse)\\n\\n(vinyl crackle drifts)\\n\\n(ambient pads rise)\\n\\n(bass weight builds)\\n\\n[Verse]\\n\\n(rolling sub bass)\\n\\n(woodblock clicks)\\n\\n(modular pulse)\\n\\n(closed hats shuffle)\\n\\n[Chorus]\\n\\n(dub delay stabs)\\n\\n(filter open wide)\\n\\n(Voltage Pressure)\\n\\n(Voltage Pressure)\\n\\n(Voltage Pressure)\\n\\n(Voltage Pressure)\\n\\nVoltage\\n\\nVoltage\\n\\nVoltage\\n\\nVoltage\\n\\n[Hook]\\n\\n(Velocity Rush)\\n\\n(Velocity Rush)\\n\\n(Velocity Rush)\\n\\n(Velocity Rush)\\n\\nVoltage\\n\\nVoltage\\n\\n[Bridge]\\n\\n(stripped low-end)\\n\\n(ambient wash drifts)\\n\\n(tape delay echoes)\\n\\n(reese swells deep)\\n\\n[Drop]\\n\\n(heavy sub drops)\\n\\n(kick re-locks tight)\\n\\n(full percussions hit)\\n\\n(neuro stab cuts)\\n\\n[Verse]\\n\\n(sub bassline evolves)\\n\\n(closed hats shuffle)\\n\\n(dub stabs echo)\\n\\n(ghost snare hits)\\n\\n[Chorus]\\n\\n(full harmonic groove)\\n\\n(resonant filter sweep)\\n\\n(Voltage Pressure)\\n\\n(Voltage Pressure)\\n\\n(Voltage Pressure)\\n\\n(Voltage Pressure)\\n\\nVoltage\\n\\nVoltage\\n\\nVoltage\\n\\nVoltage\\n\\n[Breakdown]\\n\\n(kick drops out)\\n\\n(cavernous echo)\\n\\n(reverb tails fade)\\n\\n(noise riser builds)\\n\\n[Drop]\\n\\n(sub-bass return)\\n\\n(crisp 909 kick)\\n\\n(driving hats)\\n\\n(modular percussion)\\n\\n[Outro]\\n\\n(instruments filter out)\\n\\n(isolated kick)\\n\\n(hats fade)\\n\\n(clean tail)", "prompt": "Subphase delivers a 171 BPM neurofunk Drum & Bass journey. Rolling two-step breakbeats, ghost snares, reese sub-bass, and metallic percussion. DJ-mixable intro, progressive groove changes, modular sound design, and a clean outro. No EDM drops, no supersaws.", "bitrate": 256000, "sample_rate": 44100}}	cmtg2tf7s0023ln2i3oqdwu31	2026-08-30 17:21:28.654	2026-08-30 17:31:58.106	Subphase
cmtfqgyjm000kln2iy7maxm2c	Hidden Conduit	MINIMAL_DEEP_TECH	BUFFERED	/data/media/cmtfqgyjm000kln2iy7maxm2c.mp3	99.552653	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(kick groove)\\n\\n(hats enter)\\n\\n(vinyl crackle)\\n\\n(shaker pulse)\\n\\n[Verse]\\n\\n(rolling sub)\\n\\n(woodblock clicks)\\n\\n(modular pulse)\\n\\n(dub chord)\\n\\n[Chorus]\\n\\n(dub delay)\\n\\n(filter open)\\n\\nStep\\n\\nStep\\n\\nStep\\n\\nStep\\n\\n[Hook]\\n\\nStep\\n\\nStep\\n\\n[Bridge]\\n\\n(stripped low-end)\\n\\n(ambient wash)\\n\\n(tape delay)\\n\\n(resonant ping)\\n\\n[Drop]\\n\\n(heavy sub)\\n\\n(kick re-locks)\\n\\n(full percussions)\\n\\n(bouncy bass)\\n\\n[Verse]\\n\\n(sub evolves)\\n\\n(closed hats)\\n\\n(dub stabs)\\n\\n(pocket groove)\\n\\n[Chorus]\\n\\n(full harmonic)\\n\\n(resonant filter)\\n\\nStep\\n\\nStep\\n\\nStep\\n\\nStep\\n\\n[Breakdown]\\n\\n(kick drops)\\n\\n(cavernous echo)\\n\\n(reverb tails)\\n\\n(soft pad)\\n\\n[Drop]\\n\\n(sub returns)\\n\\n(crisp kick)\\n\\n(driving hats)\\n\\n(dub chord)\\n\\n[Outro]\\n\\n(instruments filter)\\n\\n(isolated kick)\\n\\n(hats fade)\\n\\n(clean tail)", "prompt": "Minimal / Deep Tech & Microhouse at 124 BPM by Static Parcel. Rolling microhouse groove, warm dub chords, bouncy sub-bass, shuffled hats, wooden percussion, vinyl texture. DJ-mixable intro, progressive builds, analogue stabs, deep resonant filter sweeps, no supersaws, no EDM drops.", "bitrate": 256000, "sample_rate": 44100}}	cmtfqgyji000iln2i499lx0ay	2026-08-30 11:35:51.779	2026-08-30 18:39:17.317	Static Parcel
cmtfqlbcw000wln2in5g8gepm	Velvet Glow	DEEP_HOUSE	BUFFERED	/data/media/cmtfqlbcw000wln2in5g8gepm.mp3	178.755918	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(warm vinyl crackle)\\n\\n(soft kick pulse)\\n\\n(ambient pad swell)\\n\\n(bass hum enters)\\n\\n[Verse]\\n\\n(rhodes chord stab)\\n\\n(soft woodblock)\\n\\n(modular synth pulse)\\n\\n(closed hat shuffle)\\n\\n[Verse]\\n\\n(bassline deepens)\\n\\n(filtered string pad)\\n\\n(rim shot click)\\n\\n(subtle dub echo)\\n\\n[Chorus]\\n\\n(full harmonic groove)\\n\\n(resonant filter open)\\n\\nGlow\\n\\nGlow\\n\\nGlow\\n\\nGlow\\n\\n[Hook]\\n\\nGlow\\n\\nGlow\\n\\n[Bridge]\\n\\n(stripped low-end)\\n\\n(ambient wash)\\n\\n(tape delay tail)\\n\\n(soft pad drift)\\n\\n[Verse]\\n\\n(rhodes melody evolves)\\n\\n(percussion layers build)\\n\\n(deep bass groove)\\n\\n(shaker rhythm enters)\\n\\n[Chorus]\\n\\n(full harmonic groove)\\n\\n(resonant filter)\\n\\nGlow\\n\\nGlow\\n\\nGlow\\n\\nGlow\\n\\n[Breakdown]\\n\\n(kick drops out)\\n\\n(cavernous echo)\\n\\n(reverb tails)\\n\\n(soft texture only)\\n\\n[Drop]\\n\\n(sub bass returns)\\n\\n(crisp 909 kick)\\n\\n(driving hats)\\n\\n(full percussions)\\n\\n[Verse]\\n\\n(acid bassline pulse)\\n\\n(dub stab chords)\\n\\n(woodblock groove)\\n\\n(rhodes motif)\\n\\n[Chorus]\\n\\n(full harmonic groove)\\n\\n(resonant filter)\\n\\nGlow\\n\\nGlow\\n\\nGlow\\n\\nGlow\\n\\n[Outro]\\n\\n(instruments filter out)\\n\\n(isolated kick)\\n\\n(hats fade slowly)\\n\\n(clean vinyl tail)", "prompt": "Deep House, 120 BPM, original artist Mira Solace. Warm Rhodes chords, deep dub bassline, 4/4 groove with shuffled hats, vinyl texture, progressive filter builds, dub delays, clean DJ-mixable intro and outro. Soulful, hypnotic, late-night basement feel.", "bitrate": 256000, "sample_rate": 44100}}	cmtfqlbcu000uln2i8yo2nm1q	2026-08-30 11:39:15.009	2026-08-30 18:22:33.717	Mira Solace
cmtfqh45g000nln2i64bisoae	Quantum Voltage	DRUM_AND_BASS	BUFFERED	/data/media/cmtfqh45g000nln2i64bisoae.mp3	166.661224	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(ambient pad)\\n\\n(dub chord stab)\\n\\n(vinyl crackle)\\n\\n(kick fades in)\\n\\n[Verse]\\n\\n(reese sub bass)\\n\\n(two-step breaks)\\n\\n(ghost snares)\\n\\n(closed hats)\\n\\n[Chorus]\\n\\n(dub echo)\\n\\n(filter sweep)\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\n[Hook]\\n\\nPulse\\n\\nPulse\\n\\n[Bridge]\\n\\n(stripped groove)\\n\\n(modular pulse)\\n\\n(woodblock clicks)\\n\\n(tape hiss)\\n\\n[Drop]\\n\\n(heavy sub drops)\\n\\n(kick re-locks)\\n\\n(full percussion)\\n\\n(dub stabs)\\n\\n[Verse]\\n\\n(sub bassline evolves)\\n\\n(rolling breaks)\\n\\n(cavernous reverb)\\n\\n(shaker groove)\\n\\n[Chorus]\\n\\n(full harmonic groove)\\n\\n(resonant filter)\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\n[Breakdown]\\n\\n(kick drops out)\\n\\n(ambient wash)\\n\\n(dub delay)\\n\\n(reverb tails)\\n\\n[Drop]\\n\\n(sub-bass returns)\\n\\n(crisp 909 kick)\\n\\n(driving hats)\\n\\n(dub chords)\\n\\n[Chorus]\\n\\n(resonant sweep)\\n\\n(filter open)\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\nPulse\\n\\n[Outro]\\n\\n(instruments filter out)\\n\\n(isolated kick)\\n\\n(hats fade)\\n\\n(clean tail)", "prompt": "Drum & Bass, 171 BPM, Subphase. Rolling two-step breakbeats, ghost snares, deep reese sub-bass, dub chords, crisp 909 kicks, progressive groove evolution, DJ-friendly intro, full breakdown, clean outro. No EDM drops, no supersaws.", "bitrate": 256000, "sample_rate": 44100}}	cmtfqh45c000lln2iiuhtwsqg	2026-08-30 11:35:59.044	2026-08-30 18:41:17.227	Subphase
cmtfqfrwe0005ln2ia81tjc7b	Sub Code Loop	MINIMAL_DEEP_TECH	BUFFERED	/data/media/cmtfqfrwe0005ln2ia81tjc7b.mp3	102.008163	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(clean kick pulse)\\n\\n(soft room tone)\\n\\n(vinyl crackle bed)\\n\\n(tiny shaker groove)\\n\\n[Verse]\\n\\n(modular sub pulse)\\n\\n(woodblock micro clicks)\\n\\n(filtered dub stab)\\n\\n(rolling closed hats)\\n\\n[Chorus]\\n\\n(deep dub chords)\\n\\n(resonant filter open)\\n\\nLoop\\n\\nLoop\\n\\nLoop\\n\\nLoop\\n\\n[Hook]\\n\\nLoop\\n\\nLoop\\n\\n[Bridge]\\n\\n(stripped low-end)\\n\\n(ambient pad wash)\\n\\n(tape delay tails)\\n\\n(cavernous reverb)\\n\\n[Drop]\\n\\n(heavy sub kick)\\n\\n(dub stab return)\\n\\n(full micro percussion)\\n\\n(acid bassline)\\n\\n[Verse]\\n\\n(sub bassline evolves)\\n\\n(closed hats shuffle)\\n\\n(dub chord stabs)\\n\\n(sidechained pulse)\\n\\n[Chorus]\\n\\n(full harmonic groove)\\n\\n(resonant filter sweep)\\n\\nLoop\\n\\nLoop\\n\\nLoop\\n\\nLoop\\n\\n[Breakdown]\\n\\n(kick drops out)\\n\\n(cavernous dub echo)\\n\\n(reverb tails bloom)\\n\\n(isolated snap)\\n\\n[Drop]\\n\\n(sub-bass return)\\n\\n(crisp 909 kick)\\n\\n(driving micro hats)\\n\\n(filtered dub chord)\\n\\n[Outro]\\n\\n(instruments filter down)\\n\\n(isolated kick pulse)\\n\\n(hats slowly fade)\\n\\n(clean silent tail)", "prompt": "120 BPM minimal deep tech microhouse by Lumen Tool. Rolling 909 micro-percussion, dubby warm stabs, deep sub-bass pulses, shifting resonant filters, hypnotic groove loops. DJ-friendly intro, progressive dub builds, no EDM drops, no supersaws. Clean mixable outro.", "bitrate": 256000, "sample_rate": 44100}}	cmtfqfrwb0003ln2ivyk0516w	2026-08-30 11:34:56.51	2026-08-30 18:32:31.717	Lumen Tool
cmtfqgbjq000eln2i6vcu2k9a	Sub Code Loop	MINIMAL_DEEP_TECH	BUFFERED	/data/media/cmtfqgbjq000eln2i6vcu2k9a.mp3	194.272653	{"model": "minimax-music-3.0", "payload": {"format": "mp3", "lyrics": "[Intro]\\n\\n(dub echo)\\n\\n(soft kick)\\n\\n(vinyl crackle)\\n\\n(filtered pulse)\\n\\n[Verse]\\n\\n(swing hats)\\n\\n(wood bongos)\\n\\n(modular sub)\\n\\n(shaker groove)\\n\\n(Pre-Chorus)\\n\\n(resonant stab)\\n\\n(filter sweep)\\n\\n(rim click)\\n\\n(dub chord)\\n\\n[Chorus]\\n\\n(full groove)\\n\\n(deep bass)\\n\\nLoop\\n\\nLoop\\n\\nLoop\\n\\nLoop\\n\\n[Hook]\\n\\nLoop\\n\\nLoop\\n\\n[Verse]\\n\\n(bouncy bass)\\n\\n(micro percussion)\\n\\n(clap texture)\\n\\n(rolling hats)\\n\\n(Pre-Chorus)\\n\\n(synth stabs)\\n\\n(dub delay)\\n\\n(rhythmic pulse)\\n\\n(open hat)\\n\\n[Chorus]\\n\\n(dubby groove)\\n\\n(swing tech)\\n\\nLoop\\n\\nLoop\\n\\nLoop\\n\\nLoop\\n\\n[Hook]\\n\\nLoop\\n\\nLoop\\n\\n[Bridge]\\n\\n(stripped elements)\\n\\n(ambient pad)\\n\\n(tape hiss)\\n\\n(sub pulse)\\n\\n[Breakdown]\\n\\n(kick drops)\\n\\n(cavernous space)\\n\\n(reverb wash)\\n\\n(soft pluck)\\n\\n[Chorus]\\n\\n(full drive)\\n\\n(filter open)\\n\\nLoop\\n\\nLoop\\n\\nLoop\\n\\nLoop\\n\\n[Hook]\\n\\nLoop\\n\\nLoop\\n\\n[Verse]\\n\\n(tech groove)\\n\\n(bass shift)\\n\\n(percussion cut)\\n\\n(step pulse)\\n\\n[Chorus]\\n\\n(deep tech)\\n\\n(rolling loop)\\n\\nLoop\\n\\nLoop\\n\\nLoop\\n\\nLoop\\n\\n[Hook]\\n\\nLoop\\n\\nLoop\\n\\n[Outro]\\n\\n(instruments filter)\\n\\n(isolated kick)\\n\\n(hats fade)\\n\\n(clean tail)", "prompt": "120 BPM minimal deep tech microhouse by Lumen Tool. Rolling 909 micro-percussion, swung shakers, groovy wooden bongos, dubby chords, analog sub bass, warm stabs. DJ-mixable intro, progressive groove development, stripped breakdown, hypnotic dub textures, sound design, clean outro.", "bitrate": 256000, "sample_rate": 44100}}	cmtfqgbjm000cln2ikynruxsq	2026-08-30 11:35:21.974	2026-08-30 18:37:36.479	Lumen Tool
\.


--
-- Data for Name: _prisma_migrations; Type: TABLE DATA; Schema: public; Owner: radio
--

COPY public._prisma_migrations (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) FROM stdin;
b7a7985d-f33f-430c-8719-00821700f081	50ef63277988e2f2632a107433ddcb661dbe4edbf5fb18b1c63a94b08801cf91	2026-08-30 11:29:23.931932+00	20260830000000_init	\N	\N	2026-08-30 11:29:23.891919+00	1
3d20153b-ff32-4a10-9158-97b77fa6ec7c	b9168f6882d83a9a94bcfb996e506ede209b89bcd27cda2663bc45155fae9ad6	2026-08-30 11:29:23.939847+00	20260830010000_add_drum_and_bass_artist	\N	\N	2026-08-30 11:29:23.933678+00	1
\.


--
-- Name: Recipe Recipe_pkey; Type: CONSTRAINT; Schema: public; Owner: radio
--

ALTER TABLE ONLY public."Recipe"
    ADD CONSTRAINT "Recipe_pkey" PRIMARY KEY (id);


--
-- Name: Track Track_pkey; Type: CONSTRAINT; Schema: public; Owner: radio
--

ALTER TABLE ONLY public."Track"
    ADD CONSTRAINT "Track_pkey" PRIMARY KEY (id);


--
-- Name: _prisma_migrations _prisma_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: radio
--

ALTER TABLE ONLY public._prisma_migrations
    ADD CONSTRAINT _prisma_migrations_pkey PRIMARY KEY (id);


--
-- Name: Track Track_recipeId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: radio
--

ALTER TABLE ONLY public."Track"
    ADD CONSTRAINT "Track_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES public."Recipe"(id);


--
-- PostgreSQL database dump complete
--

\unrestrict sVoCc97l6YrJpHKZpfUaeCnJvO6FXZgsPVfBsx1t9LcvAz7CVWcIVObInXMoEnW

