CREATE TYPE "Genre" AS ENUM ('DEEP_HOUSE','MINIMAL_DEEP_TECH','SOULFUL_HOUSE');
CREATE TYPE "TrackStatus" AS ENUM ('GENERATING','CALIBRATION','BUFFERED','PLAYING','PLAYED','REJECTED','FAILED');
CREATE TABLE "Recipe" ("id" TEXT PRIMARY KEY,"genre" "Genre" NOT NULL,"prompt" TEXT NOT NULL,"approved" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Track" ("id" TEXT PRIMARY KEY,"title" TEXT NOT NULL,"genre" "Genre" NOT NULL,"status" "TrackStatus" NOT NULL DEFAULT 'GENERATING',"audioPath" TEXT,"durationSeconds" DOUBLE PRECISION,"minimaxPayload" JSONB NOT NULL,"recipeId" TEXT NOT NULL REFERENCES "Recipe"("id"),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
